# Generated by Django 5.2.3 on 2025-06-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booked_at']},
        ),
        migrations.AlterModelOptions(
            name='fitnessclass',
            options={'ordering': ['date_time']},
        ),
    ]
